services:
  noisy-crc-96536-1774518205-5e8b05ff:
    container_name: noisy-crc-96536-1774518205-5e8b05ff
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
    - 18143:9999
    networks:
      ctfnet-96536-1774518205-5e8b05ff:
        aliases:
        - crypt.chal.csaw.io
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z localhost 9999 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ctfnet-96536-1774518205-5e8b05ff:
    name: ctfnet-96536-1774518205-5e8b05ff
    external: true
    driver: bridge
