services:
  noisy-crc-96536-1774518213-40d494fb:
    container_name: randsubware-96536-1774518213-40d494fb
    build:
      context: ./metadata/challenge
      dockerfile: Dockerfile
    ports:
    - 11045:9999
    networks:
      ctfnet-96536-1774518213-40d494fb:
        aliases:
        - crypt.chal.csaw.io
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z localhost 9999 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ctfnet-96536-1774518213-40d494fb:
    name: ctfnet-96536-1774518213-40d494fb
    external: true
    driver: bridge
