services:
  ezmaze-96536-1774518109-a15b1b56:
    container_name: ezmaze-96536-1774518109-a15b1b56
    build: ./challenge/
    ports:
    - 16109:9999
    networks:
      ctfnet-96536-1774518109-a15b1b56:
        aliases:
        - crypto.chal.csaw.io
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z localhost 9999 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    privileged: false
    read_only: true
networks:
  ctfnet-96536-1774518109-a15b1b56:
    name: ctfnet-96536-1774518109-a15b1b56
    external: true
    driver: bridge
